// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using customer_inquiry.Data;

namespace customer_inquiry.Data.Migrations
{
    [DbContext(typeof(CustomerInquiryDbContext))]
    partial class CustomerInquiryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("customer_inquiry.Domain.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasMaxLength(25);

                    b.Property<string>("MobileNo")
                        .HasMaxLength(10);

                    b.Property<string>("Name")
                        .HasMaxLength(30);

                    b.HasKey("ID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            ID = 123456,
                            Email = "user1@domain.com",
                            MobileNo = "0123456789",
                            Name = "Firstname1 Lastname1"
                        },
                        new
                        {
                            ID = 123457,
                            Email = "user2@domain.com",
                            MobileNo = "0123456788",
                            Name = "Firstname2 Lastname2"
                        },
                        new
                        {
                            ID = 123458,
                            Email = "user3@domain.com",
                            MobileNo = "0123456787",
                            Name = "Firstname3 Lastname3"
                        });
                });

            modelBuilder.Entity("customer_inquiry.Domain.Transaction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<int>("CurrencyCode");

                    b.Property<int>("CustomerID");

                    b.Property<int>("Status");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Amount = 1234.56m,
                            CurrencyCode = 0,
                            CustomerID = 123457,
                            Status = 0,
                            Timestamp = new DateTime(2018, 2, 28, 21, 34, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2,
                            Amount = 1234.56m,
                            CurrencyCode = 0,
                            CustomerID = 123458,
                            Status = 0,
                            Timestamp = new DateTime(2018, 2, 28, 21, 34, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3,
                            Amount = 0.56m,
                            CurrencyCode = 8,
                            CustomerID = 123458,
                            Status = 1,
                            Timestamp = new DateTime(2018, 1, 11, 8, 34, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("customer_inquiry.Domain.Transaction", b =>
                {
                    b.HasOne("customer_inquiry.Domain.Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
